[alembic]
# path to migration scripts
script_location = src/db/migrations

# template used to generate migration file names
file_template = %%(year)d%%(month).2d%%(day).2d_%%(hour).2d%%(minute).2d_%%(slug)s

# timezone to use when rendering the date within the migration file
# leave blank for UTC
# timezone =

# sys.path will be prepended with these directories so that Python can find the application
prepend_sys_path = .

# log level for alembic operations
log_level = WARNING

# log level for SQLAlchemy engine
sqlalchemy_log_level = WARNING

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
